config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'urls#index'

  resources :urls, only: %i[index create show], param: :url
  get ':short_url', to: 'urls#visit', as: :visit
	
  namespace :api do
	  namespace :v1 do
      resources :urls, only: %i[index]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
# frozen_string_literal: true

class Click < ApplicationRecord
  belongs_to :url, counter_cache: true
end

app/models/url.rb
# frozen_string_literal: true

class Url < ApplicationRecord
  validates :original_url, url: true

  validates :short_url, presence: true, uniqueness: true, case_sensitive: false,
                        length: { is: 5 }, format: { with: /[A-Z]{5}/ }

  has_many :clicks, dependent: :destroy

  scope :last_ten_records, -> { order(created_at: :desc).limit(10) }

  def daily_clicks
    clicks.where('created_at > ? AND created_at < ?', Time.now.beginning_of_month,
                 Time.now).group("DATE_TRUNC('day', created_at)").count.map.with_index do |record, index|
      [index + 1, record[1]]
    end
  end

  def browser_clicks
    clicks.group(:browser).count.to_a
  end

  def platform_clicks
    clicks.group(:platform).count.to_a
  end
end

app/controllers/api/v1/application_controller.rb
module Api
	module V1
		class ApplicantController < ActionController::API
		
		end
	end
end

app/controllers/api/v1/urls_controller.rb
module Api
	module V1
		class UrlsController < ApplicationController
			def index
				@url = Url.last_ten_records.includes(:clicks)
			end
		end
	end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
# frozen_string_literal: true

class UrlsController < ApplicationController
  before_action :set_url, only: %i[visit show]

  def index
    @url = Url.new
    @urls = Url.last_ten_records
  end

  def create
    @url = UrlCreator.call(url_params)
    flash[:notice] = 'Please add a valid URL' if @url.instance_of?(Hash)

    redirect_to root_path
  end

  def show
    return render file: "#{Rails.root}/public/404.html", layout: false, status: 404 unless @url

    @daily_clicks = @url.daily_clicks
    @browsers_clicks = @url.browser_clicks
    @platform_clicks = @url.platform_clicks
  end

  def visit
    # params[:short_url]
    return render file: "#{Rails.root}/public/404.html", layout: false, status: 404 unless @url

    browser = Browser.new(request.env['HTTP_USER_AGENT'], accept_language: 'en-us')
    @url.clicks.create(browser: browser.name, platform: browser.platform.name)
    redirect_to(@url.original_url)
  end

  private

  def set_url
    @url = Url.find_by_short_url(params[:short_url] || params[:url])
  end

  def url_params
    params.require(:url).permit(:original_url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeyUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="<%= root_path %>" class="brand-logo">HeyURL!</a>
      </div>
    </nav>
    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/stats.html.erb
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div class="row">
  <div class="col s12">
    <ul class="card-panel collection with-header">
      <li class="collection-header">
        <h4>
          Stats for <a href="https://heyurl.co/QY74T">https://heyurl.co/QY74T</a>
        </h4>
      </li>
      <li class="collection-item">Created Mar 23, 2018</li>
      <li class="collection-item">
        Original URL: <a href="drive.google.com/file/d/1VdLgSSMojWFb1GRoBAFX_eXy7oX2J...">drive.google.com/file/d/1VdLgSSMojWFb1GRoBAFX_eXy7oX2J...</a>
      </li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div id="total-clicks-chart"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s6">
    <div class="card-panel">
      <div id="platforms-chart"></div>
    </div>
  </div>

  <div class="col s6">
    <div class="card-panel">
      <div id="browsers-chart"></div>
    </div>
  </div>
</div>

<script>
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawCharts);

  function drawTotalClicksChart() {
    var data = google.visualization.arrayToDataTable([
      ['day', 'clicks'],
      ['1', 13],
      ['2', 2],
      ['3', 1],
      ['4', 7],
      ['5', 20],
      ['6', 18],
      ['7', 10],
      ['8', 20],
      ['9', 15],
      ['10', 5],
    ]);

    var options = {
      title: 'total clicks',
      haxis: {
        title: 'day of month'
      },
      vaxis: {
        title: 'clicks'
      }
    };

    var chart = new google.visualization.AreaChart(
      document.getElementById('total-clicks-chart')
    );
    chart.draw(data, options);
  }

  function drawBrowsersChart() {
    var data = google.visualization.arrayToDataTable([
      ['browser', 'clicks'],
      ['IE', 13],
      ['Firefox', 22],
      ['Chrome', 17],
      ['Safari', 7],
    ]);

    var options = {
      title: 'Browsers'
    };

    var chart = new google.visualization.PieChart(
      document.getElementById('browsers-chart')
    );
    chart.draw(data, options);
  }

  function drawPlatformsChart() {
    var data = google.visualization.arrayToDataTable([
      ['platform', 'clicks'],
      ['Windows', 13],
      ['macOS', 22],
      ['Ubuntu', 17],
      ['Other', 7],
    ]);

    var options = {
      title: 'Platform'
    };

    var chart = new google.visualization.PieChart(
      document.getElementById('platforms-chart')
    );
    chart.draw(data, options);
  }

  function drawCharts() {
    drawTotalClicksChart();
    drawBrowsersChart();
    drawPlatformsChart();
  }
 </script>

app/views/urls/index.html.erb
<% if flash[:notice] %>
  <div class="card-panel notice deep-orange"><%= flash[:notice] %></div>
<% end %>
<div class="row">
  <div class="col m12">
    <%= form_for @url do |f| %>
      <div class="card">
        <div class="card-content">
          <div class="row">
            <div class="col m8 offset-m2 center-align">
              <span class="card-title">Create a new short URL</span>
            </div>
          </div>
          <div class="row">
            <div class="col m6 offset-m2">
              <%= f.text_field :original_url, class: 'validate form-control', placeholder: 'Your original URL here' %>
            </div>
            <div class="col m2">
              <button type="submit" class="waves-effect waves-light btn">Shorten URL</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<table class="table highlight">
  <thead>
    <tr>
      <th scope="col">Short URL</th>
      <th scope="col">Original URL</th>
      <th scope="col">Created</th>
      <th scope="col">Clicks Count</th>
      <th scope="col">Stats</th>
    </tr>
  </thead>
  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <th scope="row"><%= link_to url.short_url, visit_path(url.short_url), data: { turbolinks: "false" } %></th>
        <td><a href="https://drive.google.com/file/d/1VdLgSSMojWFb1GRoBAFX_eXy7oX2J"><%= url.original_url %></a></td>
        <td><!-- Please match the same format --><%= url.created_at.strftime("%b %d, %Y") %></td>
        <td><%= url.clicks_count %></td>
        <td>
          <a href="<%= url_path(url.short_url) %>">
            <svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
              <path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
            </svg>
          </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/urls/show.html.erb
<div class="row">
  <div class="col s12">
    <ul class="card-panel collection with-header">
      <li class="collection-header">
        <h4>
          Stats for <%= visit_url(@url.short_url) %>
        </h4>
      </li>
      <li class="collection-item">Created <%= @url.created_at.strftime('%b %d, %Y') %></li>
      <li class="collection-item">
        Original URL: <%= link_to @url.original_url %>
      </li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div id="total-clicks-chart"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s6">
    <div class="card-panel">
      <div id="platforms-chart"></div>
    </div>
  </div>

  <div class="col s6">
    <div class="card-panel">
      <div id="browsers-chart"></div>
    </div>
  </div>
</div>

<script>
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawCharts);

  function drawTotalClicksChart() {
    var data = google.visualization.arrayToDataTable([
      ['day', 'clicks'],
    ].concat(<%= raw @daily_clicks %>));

    var options = {
      title: 'total clicks',
      haxis: {
        title: 'day of month'
      },
      vaxis: {
        title: 'clicks'
      }
    };

    var chart = new google.visualization.AreaChart(
      document.getElementById('total-clicks-chart')
    );
    chart.draw(data, options);
  }

  function drawBrowsersChart() {
    var data = google.visualization.arrayToDataTable([
      ['browser', 'clicks'],
    ].concat(<%= raw @browsers_clicks %>));

    var options = {
      title: 'Browsers'
    };

    var chart = new google.visualization.PieChart(
      document.getElementById('browsers-chart')
    );
    chart.draw(data, options);
  }

  function drawPlatformsChart() {
    var data = google.visualization.arrayToDataTable([
      ['platform', 'clicks'],
    ].concat(<%= raw @platform_clicks %>));

    var options = {
      title: 'Platform'
    };

    var chart = new google.visualization.PieChart(
      document.getElementById('platforms-chart')
    );
    chart.draw(data, options);
  }

  function drawCharts() {
    drawTotalClicksChart();
    drawBrowsersChart();
    drawPlatformsChart();
  }
 </script>